name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions üöÄ
on: [push]
env:
  name: adedeji
  town: norwalk
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: test env and var
        run: |
          echo "using env context - my name is ${{ env.name }} and living in ${{ env.town }}"
          echo "using vars context GITHUB_ACTION - ${{ vars.GITHUB_ACTION }}"
          echo "using vars context GITHUB_ACTOR - ${{ vars.GITHUB_ACTOR }}"
          echo "using vars context GITHUB_BASE_REF - ${{ vars.GITHUB_BASE_REF }}"
          echo "using vars context GITHUB_ENV - ${{ vars.GITHUB_ENV}}"
          echo "using vars context GITHUB_EVENT_NAME - ${{ vars.GITHUB_EVENT_NAME }}"
          echo "using vars context GITHUB_PATH - ${{ vars.GITHUB_PATH }}"
      - run: echo "üéâ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "üêß This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "üîé The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "üí° The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "üñ•Ô∏è The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "üçè This job's status is ${{ job.status }}."
